version: '3'

services:
  # Selenium Hub service
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - test_my_network

  # Chrome Node service
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_my_network

  # Firefox Node service
  firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      NODE_MAX_INSTANCES: 3
      NODE_MAX_SESSION: 3
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_my_network

  # Video service
  video:
    image: selenium/video:latest
    depends_on:
      - selenium-hub
    environment:
      VIDEO_FILE_EXTENSION: mp4
      VIDEO_FILE_NAME: live_video_test
    volumes:
      - videos:/videos
    networks:
      - test_my_network

  # Your application/test runner service
  myskeletor123:
    image: myskeletor123
    depends_on:
      - selenium-hub
    networks:
      - test_my_network

networks:
  test_my_network:
    driver: bridge

volumes:
  videos:


